#pragma once
static const char PORTAL_HTML[] = R"HTML(<!doctype html>
<html lang="pt-BR"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Light · Configuração</title><style>
*{box-sizing:border-box}body{font:16px system-ui,sans-serif;background:#f1f5f9;color:#172033;margin:0;padding:24px}main{max-width:620px;margin:auto}h1{font-size:28px}section{background:white;padding:24px;border-radius:14px;margin:18px 0;box-shadow:0 3px 16px #1720330a}label{display:block;margin:15px 0 6px;font-weight:600}select,input:not([type=checkbox]){width:100%;padding:12px;border:1px solid #b8c4d4;border-radius:7px;font:inherit}button{padding:12px 20px;border:0;border-radius:7px;background:#185adb;color:white;font:inherit;cursor:pointer;margin-top:16px}button:disabled{opacity:.5}small,p{line-height:1.5}small{color:#56657a}.status{white-space:pre-wrap;padding:12px;display:none;background:#e8efff;border-radius:8px}progress{width:100%;margin-top:16px}.names{display:grid;grid-template-columns:1fr 1fr;gap:0 16px}@media(max-width:450px){body{padding:12px}.names{grid-template-columns:1fr}}
</style><main><h1>Light</h1><p>Wi-Fi, nomes das luzes e atualização do módulo.</p>
<section id="login"><h2>Acessar painel</h2><label for="key">Senha do painel</label><input id="key" type="password" autocomplete="current-password"><button id="enter">Entrar</button><p class="status" id="loginStatus" role="status"></p></section>
<div id="panel" hidden><section><h2>Configuração</h2><p id="info"></p><form id="settings">
<label for="ssid">Rede Wi-Fi (2,4 GHz)</label><input id="ssid" maxlength="32" autocomplete="off">
<label for="wifiPassword">Senha do Wi-Fi</label><input id="wifiPassword" type="password" maxlength="63" autocomplete="new-password"><small>Deixe vazia para manter a senha da mesma rede.</small>
<label><input id="openWifi" type="checkbox"> A nova rede não tem senha</label>
<label for="module">Nome do módulo</label><input id="module" maxlength="32" required>
<div class="names" id="names"></div><small>Nomes de canais: até 16 bytes (letras acentuadas ocupam mais de um byte). Alguns aplicativos Matter mantêm nomes próprios.</small>
<label for="newKey">Nova senha do painel e da rede de configuração</label><input id="newKey" type="password" minlength="8" maxlength="63" autocomplete="new-password"><small>Use de 8 a 63 caracteres sem acentos. Deixe vazia para manter a atual.</small><br>
<button type="submit">Salvar e reiniciar</button><p class="status" id="saveStatus" role="status"></p></form></section>
<section><h2>Atualizar firmware</h2><p>Selecione o arquivo <strong>light.bin</strong> compilado para esta placa.</p><input id="firmware" type="file" accept=".bin"><button id="upload">Enviar atualização</button><progress id="progress" value="0" max="100" hidden></progress><p class="status" id="otaStatus" role="status"></p></section></div></main>
<script>
'use strict';let key='';const $=id=>document.getElementById(id);function status(id,text){$(id).textContent=text;$(id).style.display='block'}function busy(on){document.querySelectorAll('button').forEach(b=>b.disabled=on)}
for(let i=0;i<1;i++){let d=document.createElement('div'),l=document.createElement('label'),v=document.createElement('input');l.htmlFor=v.id='name'+i;l.textContent='Canal '+(i+1)+' / saida GPIO '+[35][i];v.maxLength=16;v.required=true;let pl=document.createElement('label'),sel=document.createElement('select');sel.id='input'+i;pl.htmlFor=sel.id;pl.textContent='GPIO de entrada';for(let pin of [33]){let opt=document.createElement('option');opt.value=pin;opt.textContent='GPIO '+pin;sel.append(opt)}d.append(l,v,pl,sel);$('names').append(d)}
async function api(path,options={}){options.headers={...options.headers,'X-Portal-Key':key};let r=await fetch(path,options);if(!r.ok)throw Error(await r.text());return r.json()}
$('enter').onclick=async()=>{key=$('key').value;busy(true);try{let c=await api('/api/config');$('module').value=c.module;$('ssid').value=c.ssid;for(let i=0;i<1;i++){$('name'+i).value=c.names[i];$('input'+i).value=c.inputs[i];}$('info').textContent='Versão '+c.version+' · IP '+c.ip;$('login').hidden=true;$('panel').hidden=false;$('key').value=''}catch(e){status('loginStatus',e.message)}finally{busy(false)}};
$('settings').onsubmit=async e=>{e.preventDefault();busy(true);try{let data={module:$('module').value,names:Array.from({length:1},(_,i)=>$('name'+i).value),inputs:Array.from({length:1},(_,i)=>Number($('input'+i).value)),ssid:$('ssid').value,password:$('wifiPassword').value,open:$('openWifi').checked,newKey:$('newKey').value};if(data.inputs[0]!==33)throw Error('A entrada deve usar o GPIO 33.');let r=await api('/api/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});status('saveStatus',r.message)}catch(e){status('saveStatus',e.message);busy(false)}};
$('upload').onclick=()=>{let file=$('firmware').files[0];if(!file){status('otaStatus','Selecione o light.bin.');return}busy(true);$('progress').hidden=false;let x=new XMLHttpRequest();x.open('POST','/api/ota');x.setRequestHeader('Content-Type','application/octet-stream');x.setRequestHeader('X-Portal-Key',key);x.upload.onprogress=e=>{if(e.lengthComputable)$('progress').value=100*e.loaded/e.total};x.onload=()=>{if(x.status===200){status('otaStatus','Atualização validada. A placa está reiniciando. Reabra o painel em alguns segundos.')}else{status('otaStatus',x.responseText||'Falha na atualização.');busy(false)}};x.onerror=()=>{status('otaStatus','Conexão interrompida. Confira se a placa voltou antes de tentar novamente.');busy(false)};x.send(file)};
</script></html>)HTML";
